# Lock screen after 2.5 minutes of idle
timeout 150 'omarchy-system-lock'

# Turn displays off after 5 minutes of idle, turn them back on resume
timeout 300 'omarchy-brightness-keyboard off && omarchy-brightness-display off' resume 'omarchy-system-wake'

# Lock before suspend and wake displays after resume
before-sleep 'OMARCHY_LOCK_ONLY=true omarchy-system-lock'
after-resume 'sleep 1 && omarchy-system-wake'
